services:
  frontend:
    build:
      context: ./app/frontend/
      dockerfile: Dockerfile
      target: develop
    tty: true
    stdin_open: true
    ports:
      - "3000:3000"
    volumes:
      - type: bind
        source: "./app/frontend/"
        target: "/app"
  backend:
    build:
      context: ./app/backend/
      dockerfile: Dockerfile
      target: develop
    tty: true
    stdin_open: true
    volumes:
      - type: bind
        source: "./app/backend/"
        target: "/app"
  database:
    build:
      context: ./database
      dockerfile: Dockerfile
    ports:
      - "5432:5432"
    volumes:
      - data_store:/var/lib/postgresql/data
volumes:
  data_store:
    name: data_store
