services:
  frontend:
    build:
      context: ./app/frontend/
      dockerfile: Dockerfile
      target: develop
    tty: true
    stdin_open: true
    ports:
      - "3000:3000"
    volumes:
      - type: bind
        source: "./app/frontend/"
        target: "/app"
  backend:
    build:
      context: ./app/backend/
      dockerfile: Dockerfile
    tty: true
    stdin_open: true
    volumes:
      - type: bind
        source: "./app/backend/"
        target: "/app"
